### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by Atech-Rpi** [justjim1220/MMM-NewsFeedTicker#17]
Having followed the instructions to install the ticker, when running the magic mirror,  I get errors stating [10.11.2021 11:19.09.102] [ERROR] Error: Cannot find module 'valid-url'

When I remove the Module from config.js magic mirror works fine.

I have attached a text file with the complete output of the errors.

Any help would be gratefully received.  Thanks.
[MM Errors.txt](https://github.com/justjim1220/MMM-NewsFeedTicker/files/7512480/MM.Errors.txt)

**Comment by sdetweil** [comment]
see 
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later

**Comment by Atech-Rpi** [comment]
Thank you - this worked.
