### ISSUE TITLE
Blank Screen after activating MMM-NewsFeedTicker

### ISSUE THREAD

**Issue by xIExodusIx** [justjim1220/MMM-NewsFeedTicker#18]
Hi there,
I got an blank (black) screen when activating this Module, I have MM 2.19.0 running, and at this time only one RSS-Newsticker with the costomLogo. whats going wrong?
              {
                      disabled: false,
                      module: "MMM-NewsFeedTicker",
                      position: "bottom_bar",
                      //classes: "day_scheduler",
                      config: {
                              feeds: [
                                         {
                                         title: "Tagesschau Newsticker",
                                         url: "http://www.tagesschau.de/xml/rss2",
                                         customLogo: "ts_printlogo.png"
                                         },
//                                      {
//                                      title: "USA Today",
//                                      url: "http://rssfeeds.usatoday.com/UsatodaycomNation-TopStories",
//                                      customLogo: "RSS_Syndication_Logo-USATN.png"
//                                      },
//                                      {
//                                      title: "BBC World News",
//                                      url: "http://feeds.bbci.co.uk/news/world/rss.xml#",
//                                      customLogo: "bbc_news_120x60.gif"
//                                      },
                                       ],
                              }
              },

I get no syntax errors after running "npm run config:check"!  Were is the or in which submodulw is the error? 
Please help! Thanks

**Comment by sdetweil** [comment]
see 
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later

**Comment by renttoown** [comment]
For me, I had to install valid-url and request

npm install valid-url
npm install request

**Comment by shroomzzz** [comment]
Thank you @renttoown !

**Comment by KristjanESPERANTO** [comment]
Now, after accepting PR https://github.com/justjim1220/MMM-NewsFeedTicker/pull/21 this should not be an issue anymore.
