### ISSUE TITLE
Electron Issue

### ISSUE THREAD

**Issue by Dresch360** [justjim1220/MMM-NewsFeedTicker#19]
Great module!

Getting a pesky electron error message when loading MM and any help would be greatly appreciated! Using MM 2.20.0

With default configuration. Error found: Error: Cannot find module 'valid-url'
Require stack:
- /home/pi/MagicMirror/modules/MMM-NewsFeedTicker/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

**Comment by sdetweil** [comment]
see 
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later

**Comment by Dresch360** [comment]
Greatly appreciate your help! the "npm install request" did the trick. I also really appreciate you being so generous with your knowledge and explaining everything that is going on, instead of just the quick fix. It's super helpful and expands mine, as well as others understanding of how the MM and modules work.

**Comment by sdetweil** [comment]
based on you message before I assume I also installed valid-url
