### ISSUE TITLE
Change Request/How to do?

### ISSUE THREAD

**Issue by BKeyport** [justjim1220/MMM-NewsFeedTicker#2]
Love this module, but, I'd like to see a change, or instructions on how to do it if it's in there: 

I'd like to connect articles together in such a way that it's a smoother scrolling experience. No jarring jump at the end of an article. If it's changing sources, scroll the icon with the article and scroll it into the icon position and lock it. Alternative option - scroll the icon with the article completely, and get rid of the icon on the left.  

Thanks!

**Comment by justjim1220** [comment]
I tried the first option at one time, but couldn't get it to work correctly. 

The second option was how I had it set up at first. Then decided to go the current way after talking it out with several people.

If you have a solution to make it as an option, feel free to do a pull request!

Otherwise, I'll work on it when I can.

**Comment by BKeyport** [comment]
Thanks for the reply! 

I don't have any solutions at this time, I'm just barely understanding javascript. I'm trying to learn in my time off, however. 

It's a decent tool, all the same.

**Comment by justjim1220** [comment]
> Love this module, but, I'd like to see a change, or instructions on how to do it if it's in there:
> 
> I'd like to connect articles together in such a way that it's a smoother scrolling experience. No jarring jump at the end of an article. If it's changing sources, scroll the icon with the article and scroll it into the icon position and lock it. Alternative option - scroll the icon with the article completely, and get rid of the icon on the left.
> 
> Thanks!

try this and let me know what you think...

add ythe following to your custom.css file:
`
@keyframes marqueeImage {
  0% {left: 100%;}
  100% {left: 0;}
}

.MMM-NewsFeedTicker .image {
  position: absolute;
  display: inline-block;
  vertical-align: middle;
  margin-left: 0;
  height: 100px;
  z-index: 1;
  background-color: rgb(175, 175, 175);
  animation: marqueeImage 20s linear;
}
`

**Comment by BKeyport** [comment]
I had my MM down for a couple of days, so I couldn't test. Brought it back up, got the instructions in the custom.css file above, and then it alerted me to an update, Installed the update, and now I've got *huge* text with a scrolling icon that once it hits the left of the screen, it'll pop back to center and stay.

**Comment by BKeyport** [comment]
![capture](https://user-images.githubusercontent.com/44744076/48535506-70b1b900-e860-11e8-87cb-5a4de7baf7b9.PNG)

**Comment by BKeyport** [comment]
Ended up disabling the animation for now. Couldn't get the speed correct. However, I have fixed the "Image in center" problem. Everything else is working as specified in the custom CSS. 

Here's my current custom.css entries for your module. 

@keyframes marquee {
	0% {left: 100%;}
	100% {left: -100%;}
}

@Keyframes marqueeImage {
	0% {left: 100%;}
	100% {left: 0;}
}

.MMM-NewsFeedTicker {
	font-size: 100%;
	font-weight: bold;
	width: 100%;
	height: 40px;
	line-height: 100%;
	overflow: hidden;
	background: none;
	color: none;
	margin-left: 0%;
}

.MMM-NewsFeedTicker .tickerbody {
	position: relative;
	bottom: 0;
	left: 0;
	overflow: visible;
	white-space: nowrap;
	text-align: left;
	animation: marquee 31s linear;
	vertical-align: middle;
}

.MMM-NewsFeedTicker .headline {
	position: absolute;
	padding: 0;
	padding-top: 5px;
	margin: 0 auto;
	white-space: nowrap;
}

.MMM-NewsFeedTicker .image {
	position: absolute;
	display: inline-block;
	vertical-align: middle;
	margin-left: 0;
	height: 40px;
	z-index: 1;
	background-color: #FFF;
	bottom: 0;
	left: 0px;
	/* animation: marqueeImage 24s linear; */

}
