### ISSUE TITLE
Is this a dead module?

### ISSUE THREAD

**Issue by mishmanPi** [justjim1220/MMM-NewsFeedTicker#20]
Finally got my hands on a Raspberry Pi and am putting together a magicmirror project. This module looked like a good one to use. I followed directions for installation and it does not work. There are many unresolved issues posted. Seems no one is trying to keep this module alive.

**Comment by neshkoli** [comment]
run:
npm install valid-url
npm install request

**Comment by KristjanESPERANTO** [comment]
Now, after accepting PR #21 this should not be an issue anymore.
