### ISSUE TITLE
The image for the news source is in the middle of the page

### ISSUE THREAD

**Issue by queekus** [justjim1220/MMM-NewsFeedTicker#3]
![20190107_121950](https://user-images.githubusercontent.com/46459909/50791450-bdb97680-1276-11e9-8e34-33423bb21c38.jpg)
I don't know why but the images for the news sources are in the middle of the page, and they are a little big. here is the code for the config.js file:
{
	disabled: false,
	module: "MMM-NewsFeedTicker",
	position: "bottom_bar",
	//classes: "day_scheduler",
	config: {
	    feeds: [
		{
			title: "New York Times",
			url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml",
			encoding: "UTF-8", //ISO-8859-1
			className: "myClass",
			defaultLogo : ""
		},
		
    	    ]
	}
},		
{
	disabled: false,
	module: "MMM-NewsFeedTicker",
	position: "bottom_bar",
	//classes: "day_scheduler",
	config: {
	    feeds: [
		{
			title: "USA Today",
			url: "http://rssfeeds.usatoday.com/UsatodaycomNation-TopStories",
			encoding: "UTF-8", //ISO-8859-1
			className: "myClass",
			defaultLogo : ""
		},
		
    	    ]
	}
    },

and what it looks like

**Comment by kevsfastz** [comment]
You can move the ICON to the left by setting the position to "bottom_left"

**Comment by justjim1220** [comment]
issue is fixed
Please do a git pull && npm install to update
