### ISSUE TITLE
wow - the animation is waaaay too fast

### ISSUE THREAD

**Issue by mlcampbe** [justjim1220/MMM-NewsFeedTicker#4]
I've installed this module and gotten a news feed to display but the animation of the description part of the article just flies by. You cannot even really make out any letters much less any words. I tried a different feed and it went slower so it would seem that perhaps this is due to the size of the description somehow. The original feed had very long descriptions. Is there a way to set a constant speed for all feed animation?

**Comment by sdetweil** [comment]
do you have updateInterval:  specified in your config.js config  for this module?  

the default is 60 seconds (60*1000) in milliseconds

**Comment by mlcampbe** [comment]
Ah, yes I did. I had copied the whole module config from the default newsfeed and had updateInterval set to 15000. Once I removed that it helped some. The shorter feeds are just slightly too fast but my long feed is still too fast to read. Try adding the feed https://www.trumba.com/calendars/ourvalleyevents.xml and testing it on your end and see what happens.

**Comment by sdetweil** [comment]
can u show the rest of the config?    60 seconds is a long time

**Comment by mlcampbe** [comment]
I've removed all config options from my config.js and I have this:

    {
      module: "MMM-NewsFeedTicker",
      position: "bottom_bar",
      header: "",
      config: {
        feeds: [
          {
            url: "https://www.trumba.com/calendars/ourvalleyevents.xml"
          }
        ]
      }
    },

**Comment by sdetweil** [comment]
and?  it should change the feed entry shown every 60 seconds...  (1 minute)
the default newsfeed uses 10 seconds

**Comment by mlcampbe** [comment]
Yes the newsfeed 'story' changes every 60 seconds but the problem is that the text of the story scrolls by so fast you can't read it. For example, 1 of the items scrolled across for 38 seconds and then finished and there was no text shown in the animation for the next 22 seconds until the next item started. If the scrolling took the entire 60 seconds to display then it would likely be just fine.

**Comment by sdetweil** [comment]
ah, yes scrolling.. hate it...

**Comment by sdetweil** [comment]
ok, edit MMM-NewsFeedTicker.js

change lines 255
```
  calcSpeed(100);  // one second per 100 chars of news title
```
to
```
  calcSpeed(10);  // 1 second for 10 chars of newsfeed title... may need to change smaller
```

also, change  line 265 from
```
   function calcSpeed(speed) {
```
to
```
   function calcSpeedHeader(speed) {
```
and line 275 from
```
  calcSpeed(100);
```
to
```
  calcSpeedHeader(10); // 1 second for 10 chars of newsfeed title... may need to change smalle
```

let me know

**Comment by mlcampbe** [comment]
I am not sure that the changes made any difference. I even changed the "100" to "10" and then to "1" and still not really any change I can tell. I do find it odd though that the first story goes by much faster than the 2nd story.

The first story I see is "Storytelling Workshop" and the description for that is ~2340 characters. The 2nd story I see is "Foster Parent Information Session" which is ~1270 characters. So it still seems that the speed of the scrolling is related to the size of the description.

**Comment by sdetweil** [comment]
ok, comment out line 252 
```
//     divSelector[i].style.animationDuration = timeTaken + "s";
```
and 272
```
// spanSelector[i].style.animationDuration = timeTaken + "s";
```

that will turn off changing scrolling..

**Comment by mlcampbe** [comment]
No luck on my end. But I have spent too my side and it was just a test anyway to see if this is something I wanted to add. I think I will move on as I'm not likely to continue using it even with a slower speed. It just didn't work out as I had hoped but thanks for the help.

**Comment by justjim1220** [comment]
@mlcampbe 
Apologies for not getting this issue fixed.
I am still working on it. I can't quite figure out what is going on with it.

**Comment by towerleung** [comment]
You can edit line 239 and change the value from 1000 to smaller number to make the animation speed slower (I found value 300 is quite good, tested and verified) :

`tickerBody.style.animationDuration = Math.round(this.config.updateInterval / 300) + "s";`
