### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by mumblebaj** [justjim1220/MMM-NewsFeedTicker#5]
Hi.
This is not as much an issue as a question.  How do I change the the background color of the feed to a different color, i.e. like yours in the sample screen shots?  Also, if I want to use an icon for a different feed, to I need to add the icon to the pics directory and then just leave `defaultLogo` as blank? Would I need to set `useCustomLogo` to true as well?

**Comment by justjim1220** [comment]
Apologies, that is one function I have yet to get figured out.

I have written, rewritten, and even REWRITTEN the code many times over and cannot figure it out.

**Comment by mumblebaj** [comment]
Thanks so much for the response.  I will await for when you figure it out or when I have time I will try and troll your code to see if I can figure it out.  Will let you know if I do figure it out.

Thanks again for this great module.

**Comment by justjim1220** [comment]
I have added the instructions for background color change in the ReadMe of
this repo.
I also updated the repo a little.

Still working on getting the ability to use logos not supplied by the rss.

**Comment by mumblebaj** [comment]
I may have figured out why it is not picking up the icon for my feed, the code is looking for the HTML tag "image" but in the news feed I am using the HTML tag for the icon is "enclosure"
`<enclosure url="https://scripts.24.co.za/img/sites/news24.png" length="1" type="image/png"/>`

How is the customLogo declared in the config.js file?  If I add my own logo to the pic directory, how do I reference the customLogo setting?

**Comment by justjim1220** [comment]
I have it working for the moment
Do a git pull to get updated version

Or, delete your copy and redo the git clone ...
